// The generated wire types are checked in and produced from manifest/ by go-envelopes'
// generator. Whether the checked-in file is CURRENT is `npm run gen:check` (it needs Go,
// so it is a separate CI job). This test needs no Go: it guards that the file is the
// generator's output and not a hand edit's, and that the client's hand-written
// vocabulary (terminal verbs) names only verbs the generated type declares.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { TERMINAL_VERBS } from '../dist/index.js'

const src = readFileSync(new URL('../src/generated/chatstream-types.generated.ts', import.meta.url), 'utf8')

test('the generated file carries the generator\'s header and go-envelopes\' version and manifest digest', () => {
  assert.match(src, /^\/\/ Code generated by github\.com\/hollis-labs\/go-envelopes\/codegen\. DO NOT EDIT\.\n/)
  assert.match(src, /\/\/ Source: github\.com\/hollis-labs\/go-envelopes@v\d+\.\d+\.\d+; protocol v\d+; manifest sha256:[0-9a-f]{64}\./)
})

test('every terminal verb the client names is a verb the generated Verb type declares', () => {
  const verbType = src.match(/export type ChatstreamEventVerb = ([^;]+);/)?.[1]
  assert.ok(verbType, 'ChatstreamEventVerb not found')
  for (const v of TERMINAL_VERBS) assert.ok(verbType.includes(`"${v}"`), v)
})
